export const employeeData = [
  {
    id: 1,
    name: "A.R Bayer",
    department: "Helpdesk",
    "Red Flag": 85,
    Onhold: 92,
    "Assisted Ticket": 7,
    Late: 88,
  },
  {
    id: 2,
    name: "J. Querubin",
    department: "Helpdesk",
    "Red Flag": 92,
    Onhold: 96,
    "Assisted Ticket": 5,
    Late: 90,
  },
  {
    id: 3,
    name: "A.L Valente",
    department: "Helpdesk",
    "Red Flag": 78,
    Onhold: 85,
    "Assisted Ticket": 6,
    Late: 75,
  },
  {
    id: 4,
    name: "F. Gabiana",
    department: "Helpdesk",
    "Red Flag": 90,
    Onhold: 98,
    "Assisted Ticket": 4,
    Late: 95,
  },
  {
    id: 5,
    name: "J.P Lobos",
    department: "Helpdesk",
    "Red Flag": 88,
    Onhold: 90,
    "Assisted Ticket": 8,
    Late: 82,
  },
  {
    id: 6,
    name: "D. Silva",
    department: "Helpdesk",
    "Red Flag": 95,
    Onhold: 97,
    "Assisted Ticket": 6,
    Late: 93,
  },
  {
    id: 7,
    name: "D. Caballero",
    department: "Helpdesk",
    "Red Flag": 82,
    Onhold: 88,
    "Assisted Ticket": 9,
    Late: 80,
  },
  {
    id: 8,
    name: "M. Reubal",
    department: "Helpdesk",
    "Red Flag": 87,
    Onhold: 95,
    "Assisted Ticket": 5,
    Late: 85,
  },
  {
    id: 9,
    name: "A. Gatchalian",
    department: "Helpdesk",
    "Red Flag": 80,
    Onhold: 93,
    "Assisted Ticket": 7,
    Late: 78,
  },
  {
    id: 10,
    name: "R. Moran",
    department: "Helpdesk",
    "Red Flag": 93,
    Onhold: 91,
    "Assisted Ticket": 8,
    Late: 92,
  },
  {
    id: 11,
    name: "J. Enriquez",
    department: "Helpdesk",
    "Red Flag": 86,
    Onhold: 89,
    "Assisted Ticket": 10,
    Late: 84,
  },
  {
    id: 12,
    name: "MA. C.E Enriquez",
    department: "Helpdesk",
    "Red Flag": 91,
    Onhold: 99,
    "Assisted Ticket": 4,
    Late: 96,
  },
  {
    id: 13,
    name: "A. Juarez",
    department: "Helpdesk",
    "Red Flag": 84,
    Onhold: 87,
    "Assisted Ticket": 9,
    Late: 81,
  },
  {
    id: 14,
    name: "C. Cabiluna",
    department: "Helpdesk",
    "Red Flag": 89,
    Onhold: 94,
    "Assisted Ticket": 6,
    Late: 86,
  },
  {
    id: 15,
    name: "G. Alunan",
    department: "Helpdesk",
    "Red Flag": 77,
    Onhold: 83,
    "Assisted Ticket": 8,
    Late: 79,
  },
  {
    id: 16,
    name: "J. Flores",
    department: "Helpdesk",
    "Red Flag": 94,
    Onhold: 96,
    "Assisted Ticket": 5,
    Late: 91,
  },
  {
    id: 17,
    name: "J.A Matarong",
    department: "Helpdesk",
    "Red Flag": 81,
    Onhold: 86,
    "Assisted Ticket": 7,
    Late: 83,
  },
  {
    id: 18,
    name: "L. Abregana",
    department: "Helpdesk",
    "Red Flag": 88,
    Onhold: 92,
    "Assisted Ticket": 6,
    Late: 87,
  },
  {
    id: 19,
    name: "L. Unabia",
    department: "Helpdesk",
    "Red Flag": 85,
    Onhold: 90,
    "Assisted Ticket": 8,
    Late: 84,
  },
]
